**

!README.md
!Dockerfile.ngc
!Dockerfile.ngc.dockerignore
!ngc_app.py
!fal_serverless_app.py

!configs/
!configs/**

!integration/
!integration/**

!blueprints/
!blueprints/aiq/
!blueprints/aiq/**
!blueprints/signal-discovery/
!blueprints/signal-discovery/**

!cufolio/
!cufolio/**

**/.DS_Store
**/__pycache__/
**/*.pyc
**/*.pyo
**/.venv/
**/node_modules/
